// Rust source generated by the extension ("Generate test" on a DOM node or a Tauri
// command). Kept free of `vscode` imports so it can be tested under plain Node.
//
// Everything interpolated into a Rust string literal is escaped: DOM accessible names and
// ref ids are PAGE-controlled, so an unescaped `"` let a page inject Rust that runs on
// `cargo test` (round-4 audit R4-VSC1).

import type { DomNode } from "./client";

// Bidi overrides/isolates and other invisible format characters: rustc rejects a raw one in
// a literal (`text_direction_codepoint_in_literal`), and they hide what the code really says.
const NEEDS_UNICODE_ESCAPE = /[\p{Cc}\p{Cf}\p{Co}\p{Cn}\p{Zl}\p{Zp}]/u;

/**
 * Escape `s` for the inside of a Rust `"…"` string literal — the same rules as
 * `victauri-core`'s `escape_rust_str` (Rust's `char::escape_debug`, minus the needless `\'`):
 * backslash, double quote, `\n` `\r` `\t` `\0`, and every control / format / bidi /
 * unassigned character as `\u{…}`. A lone UTF-16 surrogate (not a valid Rust `char`) becomes
 * U+FFFD.
 */
export function escapeRustStr(s: string): string {
  let out = "";
  for (const ch of s) {
    const cp = ch.codePointAt(0) ?? 0xfffd;
    if (cp >= 0xd800 && cp <= 0xdfff) {
      out += "\\u{fffd}";
      continue;
    }
    switch (ch) {
      case "\\":
        out += "\\\\";
        continue;
      case '"':
        out += '\\"';
        continue;
      case "\n":
        out += "\\n";
        continue;
      case "\r":
        out += "\\r";
        continue;
      case "\t":
        out += "\\t";
        continue;
      case "\0":
        out += "\\0";
        continue;
    }
    out += NEEDS_UNICODE_ESCAPE.test(ch) ? `\\u{${cp.toString(16)}}` : ch;
  }
  return out;
}

/** A Rust string literal (quotes included) holding `s`. */
export function rustStr(s: string): string {
  return `"${escapeRustStr(s)}"`;
}

/** The `e2e_test!` generated for a DOM Explorer node ("Generate Test for Element"). */
export function generateElementTest(node: DomNode): string {
  const lines: string[] = [];
  lines.push("e2e_test!(test_element, |client| async move {");

  if (node.ref_id) {
    const refId = rustStr(node.ref_id);
    if (node.tag === "input" || node.tag === "textarea") {
      lines.push(`    client.fill(${refId}, "test value").await.unwrap();`);
    } else if (node.tag === "button" || node.tag === "a") {
      lines.push(`    client.click(${refId}).await.unwrap();`);
    } else if (node.name) {
      lines.push(
        `    Locator::text(${rustStr(node.name)})`,
        `        .expect(&mut client)`,
        `        .to_be_visible()`,
        `        .await`,
        `        .unwrap();`
      );
    }
  }

  lines.push("});");
  return lines.join("\n");
}

/**
 * The `e2e_test!` generated for a `#[tauri::command]` ("Generate Victauri test" CodeLens).
 * `fnName` comes from a `\w+` match, but it is still escaped where it lands in a literal and
 * reduced to identifier characters where it lands in the test's name.
 */
export function generateCommandTest(fnName: string): string {
  const ident = fnName.replace(/[^A-Za-z0-9_]/g, "_");
  const name = escapeRustStr(fnName);
  // Inside `assert!`'s format string the name's own braces must be doubled too — before
  // escaping, so the braces of a `\u{…}` escape are left alone.
  const fmtName = escapeRustStr(fnName.replace(/[{}]/g, (b) => b + b));
  return `e2e_test!(test_${ident}, |client| async move {
    let result = client
        .invoke_command("${name}", None)
        .await
        .unwrap();

    // Verify the command executed successfully
    assert!(result.is_object() || result.is_string() || result.is_number(),
        "${fmtName} should return a value, got: {result}");
});
`;
}
